### ISSUE TITLE
New Role: Sleeper

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/addon-ideas#14]
The sleeper is a person playing in the traitor team that doesn't know about it. He sees his role and team as a normal innocent player, but once every traitor died, he switches his team to the traitor team and sees his real role.

- the traitors should be able to see his role to prevent him being killed too early
- the traitors can not win if only they and the sleeper are alive since he plays in the innocent team until every traitor died
- the sleeper can win with the innocent as long he is innocent and can win as a traitor when he is a traitor

**Comment by Lunethia** [comment]
Okay here's a new draft on this one.

### The Sleeper

**Description** The Sleeper is an innocent with a secret, since he can become a traitor if a condition is met.

**Win condition and alignment** At the start of the round the Sleeper plays in the innocent team and wins with them.

**Gameplay and Abilities** 

- The Sleeper will know that he is a sleeper and be part of the innocent team and should play to win with the innocents.

- If the last traitor dies but the round doesn't end, which could happen if there is another non-traitor role that opposes the innocents such as the Jackal left alive the Sleeper will become a Traitor.

- Once the Sleeper awakens and becomes a traitor he will no longer be able to win with the innocents and has to eliminate all non-traitors.

- If the Sleeper is able to somehow have another Traitor alive after becoming a traitor himself he will stay a Traitor until the round ends.

- The Sleeper turning could be announced with an EPOP. (I quite love them)

**Would play best with**

- Jackal
- CerealKiller
- Necromancer
- Infected

**Comment by Pythagorion** [comment]
> Okay here's a new draft on this one.
> 
> ### The Sleeper
> **Description** The Sleeper is an innocent with a secret, since he can become a traitor if a condition is met.
> 
> **Win condition and alignment** At the start of the round the Sleeper plays in the innocent team and wins with them.
> 
> **Gameplay and Abilities**
> 
> * The Sleeper will know that he is a sleeper and be part of the innocent team and should play to win with the innocents.
> * If the last traitor dies but the round doesn't end, which could happen if there is another non-traitor role that opposes the innocents such as the Jackal left alive the Sleeper will become a Traitor.
> * Once the Sleeper awakens and becomes a traitor he will no longer be able to win with the innocents and has to eliminate all non-traitors.
> * If the Sleeper is able to somehow have another Traitor alive after becoming a traitor himself he will stay a Traitor until the round ends.
> * The Sleeper turning could be announced with an EPOP. (I quite love them)
> 
> **Would play best with**
> 
> * Jackal
> * CerealKiller
> * Necromancer
> * Infected

"KelloggsKiller" **badum tss**

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/756.
