### ISSUE TITLE
Decomposition of corpses

### ISSUE THREAD

**Issue by dok441** [TTT-2/addon-ideas#19]
https://pastebin.com/qdMJErRn
Можете адаптировать данный скрипт, он работает на 50%, то есть, когда труп становится в 1 фазе, когда только может проверить детектив, он не работает и детектив уже не может определить труп.

**Comment by Histalek** [comment]
there is a significantly newer Workshop addon found here: https://steamcommunity.com/sharedfiles/filedetails/?id=1605903001 . 

As this is neither an idea for a new addon (this issue was moved into this repository because of the label `NEW Addon`) nor a problem with ttt2 i will close it.

Feel free to try the version i linked above, maybe the problem was fixed in that version :)
