### ISSUE TITLE
New Role: Phantom

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/addon-ideas#22]
# The Phantom

**Description:** The phantom is a role that spawns alone and plays in his own team. However, like the necromancer, he can bring back dead players. Unlike zombies from the necromancer, his revived players can't interact in a normal way with the world.

**Wincondition:**

## Role Design:

- the phantom spawns alone in his own team
- he can revive dead players as ghosts, it shouldn't be a normal defibrillator but some sort of ritual
- ghosts are invisible and invincible to normal players, the phantom can see his ghosts with a wallhack
- haunted players can kill ghosts
- ghosts leave a trail behind them if they are not sneaking
- ghosts can haunt players who then receive the "haunted" status
- a dead ghost spawns no ragdoll and can therefore not be revived or inspected
- ghosts have only one weapon in their equipment - the haunter weapon (better name needed!)

## The Haunter Weapon
- ghosts spawn with this weapon
- primary attack is used to haunt players, secondary attack is used to scare haunted players
- both actions have to be charged by holding down the respective key
- it slowly decharges when no key is pressed anymore
- once the weapon is charged, the key has to be released while looking at a player
- while his device is charging, he is visible to haunted players nearby, the ghost has a wallhack for those players that are able to see him, the haunted players have also a wallhack for all ghosts in the area that are charging their device
- if a player received a scare from a ghost, different scenarios happen, e.g: frozen is place for 5 seconds while using the active weapon to shoot at random directions and losing health
- using the device on a player drains the charge to 0, if it was a scare event, the strength depends on the charge value
- maybe the lost health in a scare event is given to all players of the phantom team
- maybe the charge of the wepaon also acts a a shield, shooting at a ghost rapidly decreases the charge

## To Discuss:
- what exactly is his wincondition? should he haunt all (or a certain percentage) of players? Or does he win if only players from his team are left?
- how to balance this in a good way

---

**Hint:** I merged some ideas from the original phantom idea (https://github.com/TTT-2/addon-ideas/issues/13) to this role. The original phantom is too close to the "Demonic Posession" item.

**Comment by Skatcat** [comment]
It almost seems a little bit meek for an evil role... I would probably prefer getting any other role over Phantom, to be honest.

Maybe repurpose it as someone on the Inno/Traitor team?

**Comment by Lunethia** [comment]
I like skatcats idea. This could be merged into the traitor team as a kind of traitor specialist.

Another property of someone who got reincarnated as a ghost could be that defibrillators don't work on their body anymore, since I think the ragdoll of their prior body should remain on the ground, right, or further that they cannot be reanimated, as long as they are ghosts, at all.?

I also would like you to describe the "haunt" event for me, since I don't think I entirely understood it yet.
Furthermore do I think that the health loss is pretty annoying considering it's just a scare.
ALSO, considering his win condition when he is his own team, it should be haunting all other living players.


ALSO, the big problem that I see with this role is, that dead players have to cooperate with their summoner. Some players might right out refuse to help out their new overlord to win with their prior team instead.
Which means that anyone that became a ghost should be handled as part of the Phantoms team and win with him.
Considering that I would also suggest that if at any point the Phantom dies, all ghosts also die and will from that point on be in the original teams they were in before becoming a ghost.
I might have some more points to look at, but first please explain the haunting to me.

I also dislike this basically being a demonic posession wielding maniac btw. Could we come up with a different solution that doesn't just ruin other players (AND ESPECIALLY MY) playing experience by random shooting, switching weapons and movement inputs? :p

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/761.
