### ISSUE TITLE
New Role: The Doctor (Neutral Role)

### ISSUE THREAD

**Issue by Kreddel** [TTT-2/addon-ideas#48]
**Description:** The Doctor is on the search for a team to use his healing abilities on. Reviving his teammates provides him with credits to help his team even further.

**Win condition and alignment:** The Doctor starts without a team. In this state he is not able to win the game. He first has to offer a team his services and get hired (similar to the Pirate Captain). He will then be a part of that team and can win with it.

**Abilities and Gameplay:** 

- You first have to offer your service to a player who can accept it in some way. (This could be done similarly to the Pirate Captain)

- When your offer is accepted, every player will receive a notification:
Players in your team will see "'playername' is now working as a doctor for your team."
Players in different teams will see "'playername' is now working as a doctor for another team."
You will see who is in the team you are working for in the scoreboard, but you don't see which team it is.

- Once you have a contract, your team members will receive a passive regeneration shown by a UI icon.

- Once you have a contract, you get a defibrillator with infinite uses, which you can only use on your teammates. Reviving a teammate provides you with one credit.

- You have a detective shop, but start with zero credits.

- The Doctor cannot change his team once he has a contract.

- The Doctor loses if he has no team at the end, just like the Jester.

**Notes:**

- The defibrillator has to be on a slot where it doesn't block items from the shop.

- The defibrillator is not dropped upon the Doctor's death.

- The regeneration effect stops once the Doctor is dead.

- The Doctor gets the regeneration himself too.

- Being a Doctor in the team of the Jester basically is useless. The Jester can also decline the offer to not get the regeneration effect. The problem for the Jester will be that the Doctor basically knows the Jester's role then.

- Maybe there could be a convar to specify whether the Doctor's team is shown when his corpse is inspected.

**Comment by Lunethia** [comment]
I'd suggest changing the message for players that are not on the doctors team if the doctor joins a team to "A Doctor joined the "Role/Team"'s team."
This way the Doctor isn't publicly announced to be working against a team while revealing their identity. It's like a black market doctor hiding while providing his services kinda thing then?

Also not knowing the team but seeing all players in it can be difficult if you join the innocents. If one of them dies you can insta confirm all oother innos.

Okay, going over balance. This role is NUTS. lol. Infinite revives? Paired with credit gain? Damn. That's pretty pretty good. The passive healing also seems pretty good.

How about this, the Doc has two items, a defi, with, lets say 2 uses? But it's one of those that can fail to revive. Technology can't save everyone after all.
The other item could be bandages, or a tincture that the Doc applies on wounds to heal players. I would suggest it being a melee ability. The item could regen 50 health to the player, or even heal them to full HP. I'd also give them limited uses. Three sounds like a good number i think.

Having a shop is a huge benefit in TTT. Especially depending on items in every shop. Some servers have a lot stronger items in their shops, so you gotta factor that in when giving a lot of credits for free. 
I think the credit gain through is fine as yoou intendet it. WHenever the Doc revives someone they get a credit. THat's neet, it's like he's getting paid for doing his job!
But, as i said, with infinite revives come infinite credits. I could see a doctor teamkilling someone infinitely while dropping all sorts of stuff. Kinda broken? Yes. Definitely.

Also, why not make the contract droppable again, when we are basically copying an ability already might as well do that, otherwise make them join a random team at round start by having a dedicatet player like the bodyguard? That could be another idea. In which case the doc might die if his target dies, or something different happens. idk? You had some thoughts about this too.

On to the notes:

You cannot really set an item on a slot where it doesnt block shop items. It will always block some items. **I think**. If im wrong, please tell me.

The defis vanishing on death is a good idea. 

As said, i'd overhauul the regen effect. It would need to be very weak to not feel unfair. And it would give away everyone on the team. Just saying. :p

In terms of the jester, if we used a contract, the jester could be an exception that cannot pick it up.
Or if we used a version like the bodyguard, the jester could not be the docs target.

Maybe some of this could be considered. :)

**Comment by Kreddel** [comment]
I am totally compliant with the bandage thing instead of the regeneration. I thought about this too and it seems to be much better.

I had thought of revealing his name to nerf him because he is overpowered, as you mentioned.
Knowing who is the Doctor will make players keep an eye on him and by that make it harder for him to revive people. You could still limit the defibrillator's uses though, to balance it further.

I don't see a big difference in whether or not people see in which team the Doctor is. So that doesn't matter to me.

To not give him infinite credits I'd make him unable to deal team damage or revive teammates which commited suicide.

To the defi slot issue: You can have two items on one slot number. There is a number which determines the prioritization of a particular item in its slot. You could make it so the defi goes into the crowbar slot but you have to scroll down once to get it. That's what I know about this from my experience so far.

**Comment by Lunethia** [comment]
> To not give him infinite credits I'd make him unable to deal team damage or revive teammates which commited suicide.. <

The traitors could just shoot each other then.

**Comment by Kreddel** [comment]
You would just make it so he cannot revive teammates that were killed by another teammate in general.
The problem is getting killed by the world which would make the corpse revivable again. So maybe you could say he cannot revive people killed by the world? 
That would also nerf him again.

**Comment by Alf21** [comment]
Moved to https://github.com/TTT-2/TTT2/discussions/787.
